2021-05-09 20:29:14.789 | ERROR    | nonebot:_run_matcher:156 - Running matcher <Matcher from service_manage, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 8, in <module>
    salmon.run('run:app')
    │      └ <function run at 0x0000020DD61249D0>
    └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

  File "C:\bot\SalmonBot\salmon\__init__.py", line 30, in run
    nonebot.run(app=app)
    │       │       └ 'run:app'
    │       └ <function run at 0x0000020DD5D57B80>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
    │                │     │      │       └ {'app': 'run:app'}
    │                │     │      └ ()
    │                │     └ None
    │                └ None
    └ <function get_driver at 0x0000020DD34F9C10>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
    │       │   │      │    └ <property object at 0x0000020DF844DBD0>
    │       │   │      └ <nonebot.drivers.fastapi.Driver object at 0x0000020DD5D4AC40>
    │       │   └ 'run:app'
    │       └ <function run at 0x0000020DF82C88B0>
    └ <module 'uvicorn' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\uvicorn\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
    │      └ <function Server.run at 0x0000020DF82EB5E0>
    └ <uvicorn.main.Server object at 0x0000020DF9378550>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x0000020DF82EB670>
    │    │                  └ <uvicorn.main.Server object at 0x0000020DF9378550>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000020DD5C21820>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000020DD5C21790>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000020DD5C23310>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000020DD5BC2430>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000020DF94876D0>(<_GatheringFu...result=[True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000020DF94876D0>(<_GatheringFu...result=[True]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000020DF94876D0>(<_GatheringFu...result=[True]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000020DF94876D0>(<_GatheringFu...result=[True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
          │            │        │    │      └ {'_prefix': {'raw_command': '启用', 'command': ('启用',)}, '_suffix': {'raw_command': None, 'command': None}}
          │            │        │    └ GroupMessageEvent(time=1620563354, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │            │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x0000020DF941A250>
          │            └ <Matcher from service_manage, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x0000020DD60FC5E0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
          │       │   │    │      └ {'_prefix': {'raw_command': '启用', 'command': ('启用',)}, '_suffix': {'raw_command': None, 'command': None}}
          │       │   │    └ GroupMessageEvent(time=1620563354, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │       │   └ <nonebot.adapters.cqhttp.bot.Bot object at 0x0000020DF941A250>
          │       └ <function Matcher.run at 0x0000020DD5DDD940>
          └ <Matcher from service_manage, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
          │    │           │        │    │      └ {'_prefix': {'raw_command': '启用', 'command': ('启用',)}, '_suffix': {'raw_command': None, 'command': None}}
          │    │           │        │    └ GroupMessageEvent(time=1620563354, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │    │           │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x0000020DF941A250>
          │    │           └ <function enable_service at 0x0000020DF8489040>
          │    └ <function Matcher.run_handler at 0x0000020DD5DDD8B0>
          └ <Matcher from service_manage, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 512, in run_handler
    await handler(
          └ <function enable_service at 0x0000020DF8489040>

  File "C:\bot\SalmonBot\salmon\modules\botmanage\service_manage.py", line 71, in enable_service
    u_priv = priv.get_user_priv(bot, event)
             │    │             │    └ GroupMessageEvent(time=1620563354, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
             │    │             └ <nonebot.adapters.cqhttp.bot.Bot object at 0x0000020DF941A250>
             │    └ <function get_user_priv at 0x0000020DD6212790>
             └ <module 'salmon.priv' from 'C:\\bot\\SalmonBot\\salmon\\priv.py'>

TypeError: get_user_priv() takes 1 positional argument but 2 were given
2021-05-09 20:40:49.521 | ERROR    | nonebot:_run_matcher:156 - Running matcher <Matcher from setu, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 8, in <module>
    salmon.run('run:app')
    │      └ <function run at 0x000002C279A729D0>
    └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

  File "C:\bot\SalmonBot\salmon\__init__.py", line 30, in run
    nonebot.run(app=app)
    │       │       └ 'run:app'
    │       └ <function run at 0x000002C2796A7B80>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
    │                │     │      │       └ {'app': 'run:app'}
    │                │     │      └ ()
    │                │     └ None
    │                └ None
    └ <function get_driver at 0x000002C276E58C10>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
    │       │   │      │    └ <property object at 0x000002C21BD8CD60>
    │       │   │      └ <nonebot.drivers.fastapi.Driver object at 0x000002C27969AC40>
    │       │   └ 'run:app'
    │       └ <function run at 0x000002C21BC0A8B0>
    └ <module 'uvicorn' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\uvicorn\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
    │      └ <function Server.run at 0x000002C21BC2B5E0>
    └ <uvicorn.main.Server object at 0x000002C21CE0C1F0>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x000002C21BC2B670>
    │    │                  └ <uvicorn.main.Server object at 0x000002C21CE0C1F0>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002C279571820>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000002C279571790>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002C279573310>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002C279512430>
    └ <Handle <TaskWakeupMethWrapper object at 0x000002C21CF2CF40>(<_GatheringFu...=[True, True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000002C21CF2CF40>(<_GatheringFu...=[True, True]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000002C21CF2CF40>(<_GatheringFu...=[True, True]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000002C21CF2CF40>(<_GatheringFu...=[True, True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
          │            │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │            │        │    └ GroupMessageEvent(time=1620564047, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │            │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000002C21CEAED00>
          │            └ <Matcher from setu, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x000002C279A4C5E0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
          │       │   │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │       │   │    └ GroupMessageEvent(time=1620564047, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │       │   └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000002C21CEAED00>
          │       └ <function Matcher.run at 0x000002C27972D940>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
          │    │           │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │    │           │        │    └ GroupMessageEvent(time=1620564047, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │    │           │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000002C21CEAED00>
          │    │           └ <function random_setu at 0x000002C21CDE48B0>
          │    └ <function Matcher.run_handler at 0x000002C27972D8B0>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 512, in run_handler
    await handler(
          └ <function random_setu at 0x000002C21CDE48B0>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 67, in random_setu
    await online_setu(bot, event, keyword)
          │           │    │      └ None
          │           │    └ GroupMessageEvent(time=1620564047, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │           └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000002C21CEAED00>
          └ <function online_setu at 0x000002C21CDE4820>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 109, in online_setu
    base64_str = f"base64://{base64.b64encode(resp_data['data']).decode()}"

KeyError: 'data'
2021-05-09 20:51:55.379 | ERROR    | nonebot:_run_matcher:156 - Running matcher <Matcher from setu, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 8, in <module>
    salmon.run('run:app')
    │      └ <function run at 0x000001A8E3A829D0>
    └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

  File "C:\bot\SalmonBot\salmon\__init__.py", line 30, in run
    nonebot.run(app=app)
    │       │       └ 'run:app'
    │       └ <function run at 0x000001A8E36B7B80>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
    │                │     │      │       └ {'app': 'run:app'}
    │                │     │      └ ()
    │                │     └ None
    │                └ None
    └ <function get_driver at 0x000001A8E0E49C10>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
    │       │   │      │    └ <property object at 0x000001A885D9CC70>
    │       │   │      └ <nonebot.drivers.fastapi.Driver object at 0x000001A8E36A9C40>
    │       │   └ 'run:app'
    │       └ <function run at 0x000001A885C1A8B0>
    └ <module 'uvicorn' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\uvicorn\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
    │      └ <function Server.run at 0x000001A885C3B5E0>
    └ <uvicorn.main.Server object at 0x000001A886E2AEB0>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x000001A885C3B670>
    │    │                  └ <uvicorn.main.Server object at 0x000001A886E2AEB0>
    │    └ <function BaseEventLoop.run_until_complete at 0x000001A8E3581820>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000001A8E3581790>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001A8E3583310>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001A8E3522430>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001A886FA90D0>(<_GatheringFu...=[True, True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000001A886FA90D0>(<_GatheringFu...=[True, True]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000001A886FA90D0>(<_GatheringFu...=[True, True]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001A886FA90D0>(<_GatheringFu...=[True, True]>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
          │            │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │            │        │    └ GroupMessageEvent(time=1620564714, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │            │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001A886EBDD30>
          │            └ <Matcher from setu, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x000001A8E3A5C5E0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
          │       │   │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │       │   │    └ GroupMessageEvent(time=1620564714, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │       │   └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001A886EBDD30>
          │       └ <function Matcher.run at 0x000001A8E373D940>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
          │    │           │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │    │           │        │    └ GroupMessageEvent(time=1620564714, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │    │           │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001A886EBDD30>
          │    │           └ <function random_setu at 0x000001A886E1B310>
          │    └ <function Matcher.run_handler at 0x000001A8E373D8B0>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 512, in run_handler
    await handler(
          └ <function random_setu at 0x000001A886E1B310>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 65, in random_setu
    await online_setu(bot, event, keyword)
          │           │    │      └ ''
          │           │    └ GroupMessageEvent(time=1620564714, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │           └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001A886EBDD30>
          └ <function online_setu at 0x000001A886E1B280>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 109, in online_setu
    msg = f'「{resp_data["title"]}」/「{resp_data["author"]}」\nPID:{resp_data["id"]}\n[CQ:image,timeout=30,file={img_url}]'

KeyError: 'id'
2021-05-09 20:53:04.183 | ERROR    | setu:online_setu:113 - 发送图片https://i.pixiv.cat/img-original/img/2020/09/25/20/41/32/84604392_p0.jpg失败
2021-05-09 20:56:02.435 | ERROR    | nonebot:_run_matcher:156 - Running matcher <Matcher from setu, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 8, in <module>
    salmon.run('run:app')
    │      └ <function run at 0x000001BF2C0429D0>
    └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

  File "C:\bot\SalmonBot\salmon\__init__.py", line 30, in run
    nonebot.run(app=app)
    │       │       └ 'run:app'
    │       └ <function run at 0x000001BF2BC77B80>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 219, in run
    get_driver().run(host, port, *args, **kwargs)
    │                │     │      │       └ {'app': 'run:app'}
    │                │     │      └ ()
    │                │     └ None
    │                └ None
    └ <function get_driver at 0x000001BF29409C10>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
    │       │   │      │    └ <property object at 0x000001BF4E35CC20>
    │       │   │      └ <nonebot.drivers.fastapi.Driver object at 0x000001BF2BC69C40>
    │       │   └ 'run:app'
    │       └ <function run at 0x000001BF4E1D98B0>
    └ <module 'uvicorn' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\uvicorn\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 362, in run
    server.run()
    │      └ <function Server.run at 0x000001BF4E1FB5E0>
    └ <uvicorn.main.Server object at 0x000001BF4F287670>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x000001BF4E1FB670>
    │    │                  └ <uvicorn.main.Server object at 0x000001BF4F287670>
    │    └ <function BaseEventLoop.run_until_complete at 0x000001BF2BB41820>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000001BF2BB41790>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001BF2BB43310>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001BF2BAE2430>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001BF4F4C17F0>(<Future finished result=None>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000001BF4F4C17F0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000001BF4F4C17F0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001BF4F4C17F0>(<Future finished result=None>)>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
          │            │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │            │        │    └ GroupMessageEvent(time=1620564931, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │            │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>
          │            └ <Matcher from setu, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x000001BF2C01C5E0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
          │       │   │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │       │   │    └ GroupMessageEvent(time=1620564931, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │       │   └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>
          │       └ <function Matcher.run at 0x000001BF2BCFD940>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 527, in run
    await self.run_handler(handler, bot, event, state_)
          │    │           │        │    │      └ {'_prefix': {'raw_command': None, 'command': None}, '_suffix': {'raw_command': None, 'command': None}, 'match': <re.Match obj...
          │    │           │        │    └ GroupMessageEvent(time=1620564931, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │    │           │        └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>
          │    │           └ <function random_setu at 0x000001BF4EFAC550>
          │    └ <function Matcher.run_handler at 0x000001BF2BCFD8B0>
          └ <Matcher from setu, type=message, priority=1, temp=False>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 512, in run_handler
    await handler(
          └ <function random_setu at 0x000001BF4EFAC550>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 65, in random_setu
    await online_setu(bot, event, keyword)
          │           │    │      └ '凯露'
          │           │    └ GroupMessageEvent(time=1620564931, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │           └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>
          └ <function online_setu at 0x000001BF4EFAC4C0>

  File "C:\bot\SalmonBot\salmon\modules\setu\setu.py", line 110, in online_setu
    await bot.send(event, Message(msg))
          │   │    │      │       └ '「楽しんでやろうじゃないっ！」/「J_Young」\nPID:74877535\n[CQ:image,timeout=30,file=https://i.pixiv.cat/img-original/img/2019/05/24/14/48/31/...
          │   │    │      └ <class 'nonebot.adapters.cqhttp.message.Message'>
          │   │    └ GroupMessageEvent(time=1620564931, self_id=3235657949, post_type='message', sub_type='normal', user_id=1351495774, message_ty...
          │   └ <function Bot.send at 0x000001BF2C0313A0>
          └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 454, in send
    return await self.send_msg(**params)
                 │               └ {'user_id': 1351495774, 'group_id': 961581611, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                 └ <nonebot.adapters.cqhttp.bot.Bot object at 0x000001BF4F37B580>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 368, in call_api
    return _handle_api_result(await ResultStore.fetch(
           │                        │           └ <classmethod object at 0x000001BF2BD8C610>
           │                        └ <class 'nonebot.adapters.cqhttp.bot.ResultStore'>
           └ <function _handle_api_result at 0x000001BF2C01CCA0>

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 212, in fetch
    raise NetworkError("WebSocket API call timeout") from None
          └ <class 'nonebot.adapters.cqhttp.exception.NetworkError'>

nonebot.adapters.cqhttp.exception.NetworkError: <NetWorkError message=WebSocket API call timeout>
2021-05-09 21:06:43.796 | ERROR    | nonebot:receive:285 - WebSocket disconnected by peer.
2021-05-09 21:06:43.796 | ERROR    | alert:disconnect:23 - WebSocket连接已断开
